<template>
    <div class="overlay" v-if="mud.showRegister"><div class="overlay-card"><div class="overlay-header"><div><div class="card-title">注册</div><div class="card-sub">提交后会把账号回填到登录框。</div></div><button class="icon-btn" @click="mud.showRegister = false">×</button></div><div class="overlay-body stack"><div class="modal-grid"><div class="stack"><div class="field"><div class="label">ID</div><input class="input" v-model="mud.registerForm.id" /></div><div class="field"><div class="label">密码</div><input class="input" type="password" v-model="mud.registerForm.pass" /></div><div class="field"><div class="label">确认密码</div><input class="input" type="password" v-model="mud.registerForm.pass2" /></div><div class="field"><div class="label">手机号</div><input class="input" v-model="mud.registerForm.phone" /></div></div><div class="stack"><div class="field"><div class="label">邮箱</div><input class="input" v-model="mud.registerForm.email" /></div><div class="field"><div class="label">游戏昵称</div><input class="input" v-model="mud.registerForm.name" /></div><div class="field"><div class="label">性别</div><select class="select" v-model="mud.registerForm.sex"><option>男性</option><option>女性</option></select></div></div></div><div class="row end"><button class="soft-btn" @click="mud.showRegister = false">取消</button><button class="primary-btn" @click="mud.registerAccount">确认注册</button></div></div></div></div>

    <div class="overlay" v-if="mud.showSettings"><div class="overlay-card"><div class="overlay-header"><div><div class="card-title">设置</div><div class="card-sub">编码、界面、聊天高度和快捷命令。</div></div><button class="icon-btn" @click="mud.showSettings = false">×</button></div><div class="overlay-body stack"><div class="modal-grid"><div class="stack"><div class="field"><div class="label">默认编码</div><select class="select" v-model="mud.settings.encoding"><option value="utf8">utf8</option><option value="gbk">gbk</option><option value="gb2312">gb2312</option></select></div><div class="field"><div class="label">界面模式</div><select class="select" v-model="mud.settings.mode"><option value="dark">dark</option><option value="day">day</option></select></div><div class="field"><div class="label">聊天区高度</div><select class="select" v-model.number="mud.settings.chatHeight"><option :value="3">1/3</option><option :value="5">1/5</option><option :value="8">1/8</option></select></div></div><div class="stack"><div class="compact-item"><div class="row between"><strong>快捷命令</strong><span class="tag gray">localStorage</span></div><div class="mini-note">可自定义常用命令，不影响服务器协议。</div></div><div class="field-grid"><div class="field" v-for="slot in mud.quickSlots" :key="slot.id"><div class="label">{{ slot.label }}</div><input class="input" v-model="slot.cmd" /></div></div></div></div><div class="row end"><button class="soft-btn" @click="mud.showSettings = false">关闭</button><button class="primary-btn" @click="mud.saveSettings">保存设置</button></div></div></div></div>

    <div class="overlay" v-if="mud.showUserCenter"><div class="overlay-card"><div class="overlay-header"><div><div class="card-title">用户中心</div><div class="card-sub">本地账号、最近分区和保存状态。</div></div><button class="icon-btn" @click="mud.showUserCenter = false">×</button></div><div class="overlay-body stack"><div class="modal-grid"><div class="stack"><div class="field"><div class="label">用户名</div><input class="input" v-model="mud.profile.id" /></div><div class="field"><div class="label">密码</div><input class="input" type="password" v-model="mud.profile.pass" /></div><div class="field"><div class="label">邮箱</div><input class="input" v-model="mud.profile.email" /></div><div class="field"><div class="label">手机号</div><input class="input" v-model="mud.profile.phone" /></div></div><div class="stack"><div class="compact-item"><div class="row between"><strong>最近分区</strong><span class="tag gray">last_part</span></div><div class="mini-note">{{ mud.recentServerLabel }}</div></div><div class="server-list" style="max-height: 280px; overflow:auto; padding-right:2px"><div class="server-card" v-for="server in mud.servers" :key="'uc-' + server.id"><div class="server-meta"><div class="server-name">{{ server.name }}</div><div class="server-desc"><span class="tag">{{ server.host }}:{{ server.port }}</span></div></div><div class="server-actions"><button class="primary-btn" @click="mud.connectServer(server)">进入</button></div></div></div></div></div><div class="row end"><button class="soft-btn" @click="mud.showUserCenter = false">关闭</button><button class="primary-btn" @click="mud.saveProfile">保存资料</button></div></div></div></div>

    <div class="overlay" v-if="mud.showServerEditor"><div class="overlay-card"><div class="overlay-header"><div><div class="card-title">添加分区</div><div class="card-sub">手工录入服务器仅作本地保存，不影响登录获取的官方分区。</div></div><button class="icon-btn" @click="mud.showServerEditor = false">×</button></div><div class="overlay-body stack"><div class="field-grid"><div class="field full"><div class="label">名称</div><input class="input" v-model="mud.serverDraft.name" /></div><div class="field"><div class="label">IP / 域名</div><input class="input" v-model="mud.serverDraft.host" /></div><div class="field"><div class="label">端口</div><input class="input" v-model="mud.serverDraft.port" /></div><div class="field"><div class="label">编码</div><select class="select" v-model="mud.serverDraft.encoding"><option value="utf8">utf8</option><option value="gbk">gbk</option><option value="gb2312">gb2312</option></select></div><div class="field"><div class="label">备注</div><textarea class="textarea" v-model="mud.serverDraft.status"></textarea></div></div><div class="row end"><button class="soft-btn" @click="mud.showServerEditor = false">取消</button><button class="primary-btn" @click="mud.addManualServer">保存</button></div></div></div></div>
</template>

<script setup>
import { inject } from 'vue';

const mud = inject('mud');
</script>
